### ISSUE TITLE
建议，写个脚本，自动化爬取problem的相关信息

### ISSUE THREAD

**Issue by axetroy** [WindomZ/leetcode.go#2]
- [ ] 爬取问题描述，生成目录下的README
- [ ] 爬取problem页面下，GO的初始模板代码
- [ ] 生成GO测试文件
- [ ] 爬取页面相关信息，比如作者，难度等，并生成JSON/YAML文件在目录下

Example: 爬取这个页面，生成文件
```bash
# https://leetcode.com/problems/string-to-integer-atoi/description/
./bin/get string-to-integer-atoi
```

**Comment by WindomZ** [comment]
我之前就想了，最近没有什么时间行动，这里简化下需求：
- [x] 爬取问题description，生成目录下的README
- [x] 生成Go初始模板代码
- [x] 生成Go初始测试单元模版

**Comment by WindomZ** [comment]
[WindomZ/leetcode-init](https://github.com/WindomZ/leetcode-init)
